### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by dsuh93** [calebjo/willow#1]
Great job Caleb! Just a couple comments for your revision

# MVP List
​
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the MVP List or ones clarified with the PM
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points
​
### Comments
- [x] swap order of listings and maps, easier to work with maps once you actually have listings on the page to populate your maps markers with 
- [x] Saved Homes/Saved Searches: make it clear that part of this is CRUD, include a bullet that says users can save a home, view saved homes, and unsave homes

**Comment by calebjo** [comment]
Thanks for the feedback! I've incorporated the changes.
