### ISSUE TITLE
Design Docs

### ISSUE THREAD

**Issue by samantha-lilly** [calebjo/willow#3]
Hi Caleb,

I have reviewed your
-MVPs
-schema
-backend routes
-sample state

- in your schema- do you need to have the `saved_searches` joins table? you already have the foreign key in the table and already have that link between `users` and `saved_searches`
- ^ does it have some different type of functionality than a regular search? are all of the searches 'saved' upon creating a search?
- message me about to above to determine if we need to change the backend routes at all for the saved_searches

everything else looks good so far! I am excited about your project!

**Comment by calebjo** [comment]
Thanks for the feedback!

I've removed the `saved_searches` table from the schema/backend routes/sample state documents.
